FROM node:14.7.0-alpine3.12 as build
WORKDIR /app
COPY ./package.json /app
RUN npm install
COPY . .

# .ENV al compilar
ARG GENERATE_SOURCEMAP
ARG APP_API_BASE_URL
ARG APP_LOGIN_URL
ARG APP_OCP_APIM_SUBSCRIPTION_KEY
ARG APP_OCP_APIM_SUBSCRIPTION_APIS_KEY
ARG APP_OCP_APIM_SUBSCRIPTION_LOGIN_KEY
ARG APP_OFFICIAL_URL
ARG APP_LOGIN_SUSCRIPTION_KEY

# .ENV 
ENV GENERATE_SOURCEMAP=${GENERATE_SOURCEMAP}
ENV REACT_APP_API_BASE_URL=${APP_API_BASE_URL}
ENV REACT_APP_LOGIN_URL=${APP_LOGIN_URL}
ENV REACT_APP_OCP_APIM_SUBSCRIPTION_KEY=${APP_OCP_APIM_SUBSCRIPTION_KEY}
ENV REACT_APP_OCP_APIM_SUBSCRIPTION_APIS_KEY=${APP_OCP_APIM_SUBSCRIPTION_APIS_KEY}
ENV REACT_APP_OCP_APIM_SUBSCRIPTION_LOGIN_KEY=${APP_OCP_APIM_SUBSCRIPTION_LOGIN_KEY}
ENV REACT_APP_OFFICIAL_URL=${APP_OFFICIAL_URL}
ENV REACT_APP_LOGIN_SUSCRIPTION_KEY=${APP_LOGIN_SUSCRIPTION_KEY}

# Compilacion app
RUN npm run build

FROM nginx:1.19.1 AS publish
RUN apt-get update && apt-get install -y nginx-extras
WORKDIR /app
COPY --from=build /app/build /var/www
# Nginx config
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
ENTRYPOINT ["nginx","-g","daemon off;"]