export const createUserRequestNames = {
  costumer: "Tipo cliente*",
  office: "Empresa*",
  society: "Sociedad*",

  officeType: "codeEnterprise",
  costumerType: "codeAccountGroup",
  societyType: "codePartnership",
};

export const titlesTooltip = {
  company: "Empresa en la cual solicita crear el cliente",
  costumer:
    "Cliente nacional aplica para operaciones dadas en Colombia y extranjeros aquellos cuya operación se da en paises diferentes a Colombia, es decir según el país donde esté registrada la empresa o persona natural.",
};

export const titlesWizard = [
  { number: 1, name: "Información general" },
  { number: 2, name: "Información área ventas" },
  { number: 3, name: "Información fiscal" },
  { number: 4, name: "Documentos anexos" },
];

export const generalFormNames = {
  typeId: "Tipo Id*",
  identification: "No. Identificación*",
  peopleType: "Tipo persona*",
  economicCode: "Código actividad econ. (CIIU)*",
  treatment: "Tratamiento*",
  companyName: "Razón social*",
  firstName: "Primer nombre*",
  secondName: "Segundo nombre",
  firstLastName: "Primer apellido*",
  secondLastName: "Segundo apellido",
  department: "Departamento*",
  city: "Ciudad*",
  RUT: "Dirección registrada RUT*",
  homeTel: "Teléfono fijo*",
  indicative: "Ind.*",
  verification: "Dig.*",
  cellPhoneTel: "Teléfono celular",
  email: "Correo electrónico*",
  legalIdentification: "No. Ident. representante legal",
  legalRepresentativeName: "Nombre Representante Legal",
  legalRepresentativeLastName: "Apellido Representante Legal",
  industryType: "Tipo de industria*",
};

export const generalFormStateNames = {
  codeTypeNif: "codeTypeNif",
  nif: "nif",
  codeTypePerson: "codeTypePerson",
  codeCIIU: "codeCIIU",
  tittle: "tittle",
  businessName: "businessName",
  firstName: "firstName",
  secondName: "secondName",
  firstSurname: "firstSurname",
  secondSurname: "secondSurname",
  codeCountry: "codeCountry",
  codeRegion: "codeRegion",
  codeCity: "codeCity",
  address: "address",
  telephone: "telephone",
  cellphone: "cellphone",
  email: "email",
  legalRepresentativeId: "legalRepresentativeId",
  legalRepresentativeName: "legalRepresentativeName",
  industryType: "typeIndustry",
};

export const CODE_DEPARTMENT = [
  { code: 4, id: "05" },
  { code: 5, id: "08" },
  { code: 1, id: "11" },
  { code: 5, id: "13" },
  { code: 8, id: "15" },
  { code: 6, id: "17" },
  { code: 8, id: "18" },
  { code: 2, id: "19" },
  { code: 5, id: "20" },
  { code: 4, id: "23" },
  { code: 1, id: "25" },
  { code: 4, id: "27" },
  { code: 8, id: "41" },
  { code: 5, id: "44" },
  { code: 5, id: "47" },
  { code: 8, id: "50" },
  { code: 2, id: "52" },
  { code: 7, id: "54" },
  { code: 6, id: "63" },
  { code: 6, id: "66" },
  { code: 7, id: "68" },
  { code: 5, id: "70" },
  { code: 8, id: "73" },
  { code: 2, id: "76" },
  { code: 7, id: "81" },
  { code: 8, id: "85" },
  { code: 8, id: "86" },
  { code: 8, id: "88" },
  { code: 8, id: "91" },
  { code: 8, id: "94" },
  { code: 8, id: "95" },
  { code: 8, id: "97" },
  { code: 8, id: "99" },
];

export const fiscalNames = {
  carbon: "Impuesto carbono (ZICB)*",
  national: "Impuesto nacional (ZINA)*",
  doorbell: "Impuesto timbre (ZITI)*",
  surcharge: "Impuesto sobretasa(ZIST)*",
  iva: "Impuesto IVA (ZIVA)*",
};

export const fiscalFormNames = {
  codeImpCarbono: "value",
  codeImpNacional: "value",
  codeImpTimbre: "value",
  codeImpSobretasa: "value",
  codeImpIVA: "value",
};

export const saleNames = {
  saleOrganization: "Organización de ventas*",
  channel: "Canal*",
  sector: "Sector*",
  saleZone: "Zona ventas*",
  creditControl: "Area control de credito*",
  transporZone: "Zona de transporte*",
  saleZone: "Zona de ventas*",
};

export const saleFormNames = {
  salesOrganizationCode: "salesOrganizationCode",
  canalCode: "canalCode",
  sectorCode: "sectorCode",
  salesAreaCode: "salesAreaCode",
  creditControlAreaCode: "creditControlAreaCode",
  transporZone: "transportZoneCode",
  saleZone: "salesAreaCode",
};

export const fileDescriptions = {
  rut: "Copia del RUT*",
  camera: "Certificado de cámara de comercio*",
  document: "Copia de cedula*",
  wash: "Anexo de prevención de lavado de activos*",
  info: "Certifico la veracidad de la información*",
  descriptionFile: "Formato .pdf y un peso maximo de 4 MB",
};

export const requestTableTitles = [
  { title: "Número de solicitud" },
  { title: "Nombre del cliente" },
  { title: "Identificación del cliente" },
  { title: "Estado" },
  { title: "Sociedad" },
  { title: "Fecha de creación" },
  { title: "" },
  { title: "" },
  { title: "" },
];

export const requestTableTitlesLevelTwo = [
  { title: "Número de solicitud" },
  { title: "Nombre del cliente" },
  { title: "Identificación del cliente" },
  { title: "Estado" },
  { title: "Fecha de creación" },
  { title: "" },
];

export const requestTableTitlesApprover = [
  { title: "Número de solicitud" },
  { title: "Nombre del cliente" },
  { title: "Identificación del cliente" },
  { title: "Estado" },
  { title: "Sociedad" },
  { title: "Fecha de creación" },
  { title: "" },
];

export const requestTableTitlesVerify = [
  { title: "Número de solicitud" },
  { title: "Nombre del cliente" },
  { title: "Identificación del cliente" },
  { title: "Nombre del asesor de Nivel 1" },
  { title: "Estado" },
  { title: "Sociedad" },
  { title: "Fecha de creación" },
  { title: "" },
];

export const requestCellNames = [
  "id",
  "businessName",
  "nif",
  "stateName",
  "codePartrnership",
  "dateCreated",
];

export const requestCellNamesLevelTwo = [
  "id",
  "businessName",
  "nif",
  "stateName",
  "dateCreated",
];

export const requestCellNamesLevelOne = [
  "id",
  "businessName",
  "nif",
  "advisorName",
  "stateName",
  "codePartrnership",
  "dateCreated",
];

export const TYPE_VIA = [
  { id: "AC", name: "AVENIDA CALLE" },
  { id: "AD", name: "ADMINISTRACIÓN" },
  { id: "ADL", name: "ADELANTE" },
  { id: "AER", name: "AEROPUERTO" },
  { id: "AG", name: "AGENCIA" },
  { id: "AGP", name: "AGRUPACIÓN" },
  { id: "AK", name: "AVENIDA CARRERA" },
  { id: "AL", name: "ALTILLO" },
  { id: "ALD", name: "AL LADO" },
  { id: "ALM", name: "ALMACÉN" },
  { id: "AP", name: "APARTAMENTO" },
  { id: "APTDO", name: "APARTADO" },
  { id: "ATR", name: "ATRÁS" },
  { id: "AUT", name: "AUTOPISTA" },
  { id: "AV", name: "AVENIDA" },
  { id: "AVIAL", name: "ANILLO VIAL" },
  { id: "BG", name: "BODEGA" },
  { id: "BL", name: "BLOQUE" },
  { id: "BLV", name: "BOULEVARD" },
  { id: "BRR", name: "BARRIO" },
  { id: "C", name: "CORREGIMIENTO" },
  { id: "CA", name: "CASA" },
  { id: "CAS", name: "CASERÍO" },
  { id: "CC", name: "CENTRO COMERCIA" },
  { id: "CD", name: "CIUDADELA" },
  { id: "CEL", name: "CÉLULA" },
  { id: "CEN", name: "CENTRO" },
  { id: "CIR", name: "CIRCULAR" },
  { id: "CL", name: "CALLE" },
  { id: "CLJ", name: "CALLEJÓN" },
  { id: "CN", name: "CAMINO" },
  { id: "CON", name: "CONJUNTO RESIDENCIA" },
  { id: "CONJ", name: "CONJUNTO" },
  { id: "CR", name: "CARRERA" },
  { id: "CRT", name: "CARRETERA" },
  { id: "CRV", name: "CIRCUNVALAR" },
  { id: "CS", name: "CONSULTORIO" },
  { id: "DG", name: "DIAGONAL" },
  { id: "DP", name: "DEPÓSITO" },
  { id: "DPTO", name: "DEPARTAMENTO" },
  { id: "DS", name: "DEPÓSITO SÓTANO" },
  { id: "ED", name: "EDIFICIO" },
  { id: "EN", name: "ENTRADA" },
  { id: "ES", name: "ESCALERA" },
  { id: "ESQ", name: "ESQUINA" },
  { id: "ET", name: "ETAPA" },
  { id: "EX", name: "EXTERIOR" },
  { id: "FCA", name: "FINCA" },
  { id: "GJ", name: "GARAJE" },
  { id: "GS", name: "GARAJE SÓTANO" },
  { id: "GT", name: "GLORIETA" },
  { id: "HC", name: "HACIENDA" },
  { id: "HG", name: "HANGAR" },
  { id: "IN", name: "INTERIOR" },
  { id: "IP", name: "INSPECCIÓN DE POLICÍA" },
  { id: "IPD", name: "INSPECCIÓN DEPARTAMENTAL" },
  { id: "IPM", name: "INSPECCIÓN MUNICIPAL" },
  { id: "KM", name: "KILÓMETRO" },
  { id: "LC", name: "LOCAL" },
  { id: "LM", name: "LOCAL MEZZANINE" },
  { id: "LT", name: "LOTE" },
  { id: "MD", name: "MÓDULO" },
  { id: "MJ", name: "MOJÓN" },
  { id: "MLL", name: "MUELLE" },
  { id: "MN", name: "MEZZANINE" },
  { id: "MZ", name: "MANZANA" },
  { id: "NOMBRE VIA", name: "VÍAS DE NOMBRE COMÚN" },
  { id: "OESTE", name: "OESTE" },
  { id: "OF", name: "OFICINA" },
  { id: "P", name: "PISO" },
  { id: "PA", name: "PARCELA" },
  { id: "PAR", name: "PARQUE" },
  { id: "PD", name: "PREDIO" },
  { id: "PH", name: "PENTHOUSE" },
  { id: "PJ", name: "PASAJE" },
  { id: "PL", name: "PLANTA" },
  { id: "PN", name: "PUENTE" },
  { id: "POR", name: "PORTERÍA" },
  { id: "POS", name: "POSTE" },
  { id: "PQ", name: "PARQUEADERO" },
  { id: "PRJ", name: "PARAJE" },
  { id: "PS", name: "PASEO" },
  { id: "PT", name: "PUESTO" },
  { id: "PW", name: "PARK WA" },
  { id: "RP", name: "ROUND POIN" },
  { id: "SA", name: "SALÓN" },
  { id: "SC", name: "SALÓN COMUNA" },
  { id: "SD", name: "SALIDA" },
  { id: "SEC", name: "SECTOR" },
  { id: "SL", name: "SOLAR" },
  { id: "SM", name: "SÚPER MANZAN" },
  { id: "SS", name: "SEMISÓTANO" },
  { id: "ST", name: "SÓTANO" },
  { id: "SUITE", name: "SUITE" },
  { id: "TER", name: "TERMINAL" },
  { id: "TERPLN", name: "TERRAPLÉN" },
  { id: "TO", name: "TORRE" },
  { id: "TV", name: "TRANSVERSAL" },
  { id: "TZ", name: "TERRAZA" },
  { id: "UN", name: "UNIDAD" },
  { id: "UR", name: "UNIDAD RESIDENCIA" },
  { id: "URB", name: "URBANIZACIÓN" },
  { id: "VRD", name: "VEREDA" },
  { id: "VTE", name: "VARIANTE" },
  { id: "ZF", name: "ZONA FRANCA" },
  { id: "ZN", name: "ZONA" },
];

export const LETTER_VIA = [
  { id: 1, name: "A" },
  { id: 2, name: "B" },
  { id: 3, name: "C" },
  { id: 4, name: "D" },
  { id: 5, name: "E" },
  { id: 6, name: "F" },
  { id: 7, name: "G" },
  { id: 8, name: "H" },
  { id: 9, name: "I" },
  { id: 10, name: "J" },
  { id: 11, name: "K" },
  { id: 12, name: "L" },
  { id: 28, name: "LL" },
  { id: 13, name: "M" },
  { id: 14, name: "N" },
  { id: 27, name: "Ñ" },
  { id: 15, name: "O" },
  { id: 16, name: "P" },
  { id: 17, name: "Q" },
  { id: 18, name: "R" },
  { id: 19, name: "S" },
  { id: 20, name: "T" },
  { id: 21, name: "U" },
  { id: 22, name: "V" },
  { id: 23, name: "W" },
  { id: 24, name: "X" },
  { id: 25, name: "Y" },
  { id: 26, name: "Z" },
];

export const BIS = [{ id: 1, name: "Bis" }];

export const QUADRANT = [
  { id: "ESTE", name: "ESTE" },
  { id: "NORTE", name: "NORTE" },
  { id: "O", name: "ORIENTE" },
  { id: "OCC", name: "OCCIDENTE" },
  { id: "SUR", name: "SUR" },
];
